export const companies = [
  { id: 1,
    title: "Company title",
    text: "Nec sem orci, turpis quam. Felis velit urna tellus lorem turpis urna lacinia non faucibus.",
    price: 10000,
    img: "/assets/images/1.svg",
    img2: "/assets/images/2.svg"
  },
  { id: 2 ,
    title: "Company title",
    text: "Nec sem orci, turpis quam. Felis velit urna tellus lorem turpis urna lacinia non faucibus.",
    price: 10000,
    img: "/assets/images/2.svg",
  },
  {
    id: 3,
    title: "Company title",
    text: "Nec sem orci, turpis quam. Felis velit urna tellus lorem turpis urna lacinia non faucibus.",
    price: 10000,
    img: "/assets/images/3.svg",
  },
  {
    id: 4,
    title: "Company title",
    text: "Nec sem orci, turpis quam. Felis velit urna tellus lorem turpis urna lacinia non faucibus.",
    price: 10000,
    img: "/assets/images/4.svg",
  },
  {
    id: 5 ,
    title: "Company title",
    text: "Nec sem orci, turpis quam. Felis velit urna tellus lorem turpis urna lacinia non faucibus.",
    price: 10000,
    img: "/assets/images/1.svg",
  },
  {
    id: 6,
    title: "Company title",
    text: "Nec sem orci, turpis quam. Felis velit urna tellus lorem turpis urna lacinia non faucibus.",
    price: 10000,
    img: "/assets/images/2.svg",
  },
  {
    id: 7,
    title: "Company title",
    text: "Nec sem orci, turpis quam. Felis velit urna tellus lorem turpis urna lacinia non faucibus.",
    price: 10000,
    img: "/assets/images/3.svg",
  },
  {
    id: 8,
    title: "Company title",
    text: "Nec sem orci, turpis quam. Felis velit urna tellus lorem turpis urna lacinia non faucibus.",
    price: 10000,
    img: "/assets/images/4.svg",
  },
  {
    id: 9,
    title: "Company title",
    text: "Nec sem orci, turpis quam. Felis velit urna tellus lorem turpis urna lacinia non faucibus.",
    price: 10000,
    img: "/assets/images/1.svg",
  },
  {
    id: 10,
    title: "Company title",
    text: "Nec sem orci, turpis quam. Felis velit urna tellus lorem turpis urna lacinia non faucibus.",
    price: 10000,
    img: "/assets/images/2.svg",
  },
  {
    id: 11,
    title: "Company title",
    text: "Nec sem orci, turpis quam. Felis velit urna tellus lorem turpis urna lacinia non faucibus.",
    price: 10000,
    img: "/assets/images/3.svg",
  },
  {
    id: 12,
    title: "Company title",
    text: "Nec sem orci, turpis quam. Felis velit urna tellus lorem turpis urna lacinia non faucibus.",
    price: 10000,
    img: "/assets/images/4.svg",
  },
];
